### ISSUE TITLE
push: Azure non-versioned remote not providing error message about not supporting versioning

### ISSUE THREAD

**Issue by glenn-t** [iterative/dvc-azure#43] opened 2023-03-16 03:14 UTC
# Bug Report

## Description

I have been trying out DVC for the first time, using an Azure remote. I mistakenly set `version_aware true`, but my Azure remote is not version enabled. When trying `dvc push`, got `unexpected error`, rather than `failed to push data to the cloud - remote 'myremote' does not support versioning`. This caused me a lot of debugging time, so an informative error would have been better.

I can see an informative error should have been produced from `test_versioning` function, but this didn't happen as the function produced an error on line `info = dest_fs.info(dest_path)`, rather than producing the desired informative error message.

The full error is below.

```
dvc push -v
2023-03-16 14:37:19,723 DEBUG: v2.50.0 (pip), CPython 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
2023-03-16 14:37:19,723 DEBUG: command: /home/glenn/Projects/dvc/.venv/bin/dvc push -v
2023-03-16 14:37:19,955 DEBUG: Pushing version-aware files to 'dvs-test/dvc'
2023-03-16 14:37:20,227 DEBUG: '['dvs-test/dvc/data/data2.csv']' file already exists, skipping                                                                    
2023-03-16 14:37:20,548 ERROR: unexpected error                                                                                                                   
Traceback (most recent call last):
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 705, in _ls_blobs
    async for next_blob in blobs:
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 149, in __anext__
    return await self.__anext__()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 152, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/async_paging.py", line 96, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 90, in _get_next_cb
    process_storage_error(error)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 83, in _get_next_cb
    return await self._command(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_container_operations.py", line 1785, in list_blob_hierarchy_segment
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified container does not exist.
RequestId:887a78c3-c01e-0077-7fa7-570344000000
Time:2023-03-16T01:37:20.5036327Z
ErrorCode:ContainerNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:887a78c3-c01e-0077-7fa7-570344000000
Time:2023-03-16T01:37:20.5036327Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/__init__.py", line 67, in wrapper
    return f(repo, *args, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/push.py", line 50, in push
    pushed += _push_worktree(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/push.py", line 119, in _push_worktree
    return push_worktree(repo, remote, targets=targets, jobs=jobs, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc/repo/worktree.py", line 176, in push_worktree
    pushed += checkout(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 102, in checkout
    entry.meta = test_versioning(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 38, in test_versioning
    info = dest_fs.info(dest_path)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 467, in info
    return self.fs.info(path, **kwargs)
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 506, in info
    return sync(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 100, in sync
    raise return_result
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/fsspec/asyn.py", line 55, in _runner
    result[0] = await coro
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 561, in _info
    out = await self._ls(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 812, in _ls
    output = await self._ls_blobs(
  File "/home/glenn/Projects/dvc/.venv/lib/python3.10/site-packages/adlfs/spec.py", line 738, in _ls_blobs
    raise FileNotFoundError
FileNotFoundError

2023-03-16 14:37:20,623 DEBUG: link type reflink is not available ([Errno 95] no more link types left to try out)
2023-03-16 14:37:20,623 DEBUG: Removing '/home/glenn/Projects/.GKTi22QwBRBYvnZLnJQW8Y.tmp'
2023-03-16 14:37:20,623 DEBUG: Removing '/home/glenn/Projects/.GKTi22QwBRBYvnZLnJQW8Y.tmp'
2023-03-16 14:37:20,624 DEBUG: Removing '/home/glenn/Projects/.GKTi22QwBRBYvnZLnJQW8Y.tmp'
2023-03-16 14:37:20,624 DEBUG: Removing '/home/glenn/Projects/dvc/.dvc/cache/.oR9jKxwCthEwWrBWfHWEfp.tmp'
2023-03-16 14:37:20,631 DEBUG: Version info for developers:
DVC version: 2.50.0 (pip)
-------------------------
Platform: Python 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/2b5af32cb49e0e43fcdab0056793557a
```

### Reproduce

1. dvc init
2. Set up a non-versioned Azure storage account with hierarchical namespacing
3. dvc remote add -d myremote azure://mycontainer/path
4. dvc remote modify myremote version_aware true
5. dvc remote modify myremote --local account_name <storage_account_name>
6. dvc remote modify --local myremote connection_string <connection_string>
7. create dummy file: data/data2.csv
8. dvc add data/data2.csv
9. dvc push

### Expected

```
dvc push                          
  0% Pushing to remote 'myremote'  | dvs-test/dvc/data/data2.csv                                                                                                                                        
ERROR: while uploading 'dvs-test/dvc/data/data2.csv', support for versioning could not be detected                                                                
ERROR: failed to push data to the cloud - remote 'myremote' does not support versioning  
```

### Environment information

**Output of `dvc doctor`:**

```console
DVC version: 2.50.0 (pip)
-------------------------
Platform: Python 3.10.4 on Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
Subprojects:
        dvc_data = 0.44.1
        dvc_objects = 0.21.1
        dvc_render = 0.2.0
        dvc_task = 0.2.0
        scmrepo = 0.1.15
Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3)
Cache types: hardlink, symlink
Cache directory: ext4 on /dev/sdc
Caches: local
Remotes: azure
Workspace directory: ext4 on /dev/sdc
Repo: dvc, git
Repo.site_cache_dir: /var/tmp/dvc/repo/2b5af32cb49e0e43fcdab0056793557a
```

**Additional Information (if any):**

The data file I was trying to push was actually uploaded to Azure during this process. Once uploaded, I was able to delete the data file and cache locally, and use `dvc pull` to successfully pull the data.

As seen in the stack trace, I was also getting an error `The specified container does not exist`. I can confirm the container does exist. When setting `version_aware false`, `dvc push` worked as expected.

**Comment by pmrowla** [comment] 2023-03-17 01:39
> Can we use [BlobServiceProperties.is_versioning_enabled](https://learn.microsoft.com/en-us/python/api/azure-mgmt-storage/azure.mgmt.storage.v2022_09_01.models.blobserviceproperties?view=azure-python) (see https://stackoverflow.com/a/75635303) to check the storage account?

Using `BlobServiceProperties` requires storage account level read permissions (and not container level read permissions). So this would not work when a user only has read permissions for the specific container used in the DVC remote.

**Comment by whiteocean016** [comment] 2023-03-18 15:38
> Thanks for looking into it. I set up a versioned Azure Storage Account, and was surprised to find I am actually getting the same problem.

I encountered the same issue (error and traceback) when pushing to a versioned azure blob storage with version_aware=True. Some files appear in the remote but non have multiple versions.

**Comment by dberenbaum** [comment] 2023-03-23 18:11
@whiteocean016 Have you enabled [blob versioning](https://learn.microsoft.com/en-us/azure/storage/blobs/versioning-overview) in Azure?

**Comment by whiteocean016** [comment] 2023-03-25 06:42
@dberenbaum Yes, I also tried it out manually by uploading and overwriting files to see if versions appear and it worked.

**Comment by dberenbaum** [comment] 2023-03-28 17:43
With working credentials, I'm not able to reproduce your issue. @pmrowla @daavoo I think you also were unable to reproduce it, correct?

@whiteocean016 @glenn-t Maybe you could share more about how to reproduce the errors you are seeing?

**Comment by dberenbaum** [comment] 2023-04-21 17:43
The same error mentioned in https://github.com/iterative/dvc-azure/issues/43#issuecomment-1472982012 was reported by another user, and now I'm able to reproduce it. @pmrowla Could you please take a look? It looks to completely break cloud versioning for Azure.

Just to confirm that I have the same error as above, here's the full output:

```
$ dvc push -v
2023-04-21 13:39:08,366 DEBUG: v2.55.0, CPython 3.10.10 on macOS-13.2.1-arm64-arm-64bit
2023-04-21 13:39:08,366 DEBUG: command: /Users/dave/miniforge3/envs/dvc/bin/dvc push -v
2023-04-21 13:39:08,690 DEBUG: Pushing version-aware files to 'test/versioned'
2023-04-21 13:39:08,969 DEBUG: '['test/versioned/dogs/dog.1001.jpg']' file already exists, skipping
2023-04-21 13:39:09,046 ERROR: unexpected error
Traceback (most recent call last):
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/adlfs/spec.py", line 705, in _ls_blobs
    async for next_blob in blobs:
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/core/async_paging.py", line 149, in __anext__
    return await self.__anext__()
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/core/async_paging.py", line 152, in __anext__
    self._page = await self._page_iterator.__anext__()
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/core/async_paging.py", line 96, in __anext__
    self._response = await self._get_next(self.continuation_token)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 90, in _get_next_cb
    process_storage_error(error)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/storage/blob/_shared/response_handlers.py", line 189, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/storage/blob/aio/_list_blobs_helper.py", line 83, in _get_next_cb
    return await self._command(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/core/tracing/decorator_async.py", line 79, in wrapper_use_tracer
    return await func(*args, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/storage/blob/_generated/aio/operations/_container_operations.py", line 1785, in list_blob_hierarchy_segment
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/azure/core/exceptions.py", line 109, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: The specified container does not exist.
RequestId:b5e514b2-e01e-0067-2078-7497e2000000
Time:2023-04-21T17:39:09.0482632Z
ErrorCode:ContainerNotFound
Content: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:b5e514b2-e01e-0067-2078-7497e2000000
Time:2023-04-21T17:39:09.0482632Z</Message></Error>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dave/Code/dvc/dvc/cli/__init__.py", line 210, in main
    ret = cmd.do_run()
  File "/Users/dave/Code/dvc/dvc/cli/command.py", line 26, in do_run
    return self.run()
  File "/Users/dave/Code/dvc/dvc/commands/data_sync.py", line 60, in run
    processed_files_count = self.repo.push(
  File "/Users/dave/Code/dvc/dvc/repo/__init__.py", line 65, in wrapper
    return f(repo, *args, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/push.py", line 50, in push
    pushed += _push_worktree(
  File "/Users/dave/Code/dvc/dvc/repo/push.py", line 119, in _push_worktree
    return push_worktree(repo, remote, targets=targets, jobs=jobs, **kwargs)
  File "/Users/dave/Code/dvc/dvc/repo/worktree.py", line 176, in push_worktree
    pushed += checkout(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 102, in checkout
    entry.meta = test_versioning(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_data/index/checkout.py", line 38, in test_versioning
    info = dest_fs.info(dest_path)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/dvc_objects/fs/base.py", line 467, in info
    return self.fs.info(path, **kwargs)
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/adlfs/spec.py", line 506, in info
    return sync(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/fsspec/asyn.py", line 98, in sync
    raise return_result
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/adlfs/spec.py", line 561, in _info
    out = await self._ls(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/adlfs/spec.py", line 812, in _ls
    output = await self._ls_blobs(
  File "/Users/dave/miniforge3/envs/dvc/lib/python3.10/site-packages/adlfs/spec.py", line 738, in _ls_blobs
    raise FileNotFoundError
FileNotFoundError

2023-04-21 13:39:09,078 DEBUG: Removing '/Users/dave/.35dFZS3N4xRxC8KgzcmsPC.tmp'
2023-04-21 13:39:09,079 DEBUG: Removing '/Users/dave/.35dFZS3N4xRxC8KgzcmsPC.tmp'
2023-04-21 13:39:09,079 DEBUG: Removing '/Users/dave/.35dFZS3N4xRxC8KgzcmsPC.tmp'
2023-04-21 13:39:09,079 DEBUG: Removing '/Users/dave/repo/.dvc/cache/.6wVhh4bAHYzFbxsMH2KnvE.tmp'
2023-04-21 13:39:09,081 DEBUG: Version info for developers:
DVC version: 2.55.0
-------------------
Platform: Python 3.10.10 on macOS-13.2.1-arm64-arm-64bit
Subprojects:
        dvc_data = 0.47.2
        dvc_objects = 0.21.1
        dvc_render = 0.3.1
        dvc_task = 0.2.0
        scmrepo = 1.0.2
Supports:
        azure (adlfs = 2023.1.0, knack = 0.10.1, azure-identity = 1.12.0),
        gdrive (pydrive2 = 1.15.3),
        gs (gcsfs = 2022.11.0),
        hdfs (fsspec = 2022.11.0, pyarrow = 11.0.0),
        http (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        https (aiohttp = 3.8.4, aiohttp-retry = 2.8.3),
        oss (ossfs = 2021.8.0),
        s3 (s3fs = 2022.11.0, boto3 = 1.24.59),
        ssh (sshfs = 2023.4.1),
        webdav (webdav4 = 0.9.8),
        webdavs (webdav4 = 0.9.8),
        webhdfs (fsspec = 2022.11.0)
Cache types: reflink, hardlink, symlink
Cache directory: apfs on /dev/disk3s1s1
Caches: local
Remotes: azure
Workspace directory: apfs on /dev/disk3s1s1
Repo: dvc, git
Repo.site_cache_dir: /Library/Caches/dvc/repo/6414c2ff59800d13bb7dc40946807396

Having any troubles? Hit us up at https://dvc.org/support, we are always happy to help!
2023-04-21 13:39:09,082 DEBUG: Analytics is disabled.
```

@glenn-t mentioned that [`self.ls.info(path)` from dvc-objects](https://github.com/iterative/dvc-objects/blob/04b12d050ea34c82e6b8ca4842cfa0c1f93b296e/src/dvc_objects/fs/base.py#L467) returns an empty result, but I get a `FileNotFoundError` there:

```
> /Users/dave/Code/dvc-objects/src/dvc_objects/fs/base.py(468)info()
-> return self.fs.info(path, **kwargs)
(Pdb) path
'test/versioned/dogs/dog.1001.jpg'
(Pdb) self.fs
<dvc_azure.spec.AzureBlobFileSystem object at 0x10340a350>
(Pdb) self.fs.info("test/versioned/dogs/dog.1001.jpg")
*** FileNotFoundError
```

**Comment by daavoo** [comment] 2023-04-25 08:39
Can reproduce. I am taking a look

**Comment by daavoo** [comment] 2023-04-25 08:56
The problem was fixed by https://github.com/fsspec/adlfs/pull/390
but the issue is that https://github.com/fsspec/adlfs hasn't released a version including that fix (the latest release was in January).

Installing `pip install git+https://github.com/fsspec/adlfs` solves the issue.
We need to ask for a new adlfs release

**Comment by efiop** [comment] 2023-04-27 14:57
Pushed 2023.4.0 https://github.com/fsspec/adlfs/issues/412

**Comment by dberenbaum** [comment] 2023-04-27 18:04
Awesome, thanks @efiop!

**Comment by dberenbaum** [comment] 2023-04-27 18:05
Bumping in dvc-azure is also a good idea.

**Closed** 2023-04-27 18:06 UTC
Labels: p0-critical

**Comment by efiop** [comment] 2023-04-27 18:09
@daavoo Thank you for the research! 🙏

**Comment by glenn-t** [comment] 2023-04-27 19:56
Thanks so much for fixing this!
